### ISSUE TITLE
Script is not working

### ISSUE THREAD

**Issue by cinetube** [SuhairZain/url-to-gdrive#1]
Script is not working

Getting error - Failed Download XHR error

**Comment by SuhairZain** [comment]
Hi, you can bypass the XHR error by using the provided proxy. Did you try checking the "Use proxy" option?

**Comment by cinetube** [comment]
Yes I have used "use proxy" option. But "use proxy" option makes the script very slow.

**Comment by SuhairZain** [comment]
The XHR error is because the server you're downloading from doesn't have CORS enabled. The proxy bypasses this restriction. If the provided proxy is slow, look at [#2](https://github.com/SuhairZain/url-to-gdrive/issues/2) to see how to use your own proxy instead. Closing this issue for now.
