### ISSUE TITLE
How to change - https://sz-node-proxy.herokuapp.com/

### ISSUE THREAD

**Issue by cinetube** [SuhairZain/url-to-gdrive#2]
How can I change - https://sz-node-proxy.herokuapp.com/?

**Comment by SuhairZain** [comment]
Hi,
For now, you can clone/fork the repo and change the [proxy](https://github.com/SuhairZain/url-to-gdrive/blob/master/src/App.jsx#L83) to one of your own, like given below:

``` javascript
- src: proxy?'https://sz-node-proxy.herokuapp.com/' + url: url,
+ src: proxy?'https://your-proxy-here.com/' + url: url,
```

And run **npm run prod** or **npm run dev** from the project root folder to create the new JS files.

I will provide a field to accept a proxy. Until then, you can use the above workaround.

**Comment by SuhairZain** [comment]
Hi @cinetube,
I've added a field to use your own proxy. Check and see if that addresses your issue. Closing this issue for now.
